name: external app prop

spring.config.import: http://${CONFIG_SERVER_HOST}:8085/
spring.datasource.platform: postgres

server.port: 8083
postgres_url: jdbc:postgresql://db:5432/postgres
postgres_usr: postgres
postgres_psw: superpswd
postgres_driver: org.postgresql.Driver
