name: external app prop
spring.datasource.platform: postgres

server.port: 8083
postgres_url: jdbc:postgresql://3.87.124.142:5432/postgres
postgres_usr: postgres
postgres_psw: superpswd
postgres_driver: org.postgresql.Driver
