name: external app prop
spring.datasource.platform: postgres

server.port: 8083
postgres_url: jdbc:postgresql://ec2-3-87-124-142.compute-1.amazonaws.com:5432/postgres
postgres_usr: postgres
postgres_psw: superpswd
postgres_driver: org.postgresql.Driver
